# Generated by Django 3.2.25 on 2024-11-19 16:16

import auth_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interim_media', auth_media.models.AuthFileField(upload_to='interim')),
                ('xaccel_media', auth_media.models.AuthFileField(upload_to='xaccel')),
                ('secure_media', auth_media.models.AuthFileField(upload_to='secure')),
            ],
        ),
    ]
